name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    if: github.repository == 'webpros-cpanel/app-csf'
    runs-on:
      group: org/cpanel-arc-image-build
    container:
      image: ghcr.io/webpros-cpanel/misc-ci-containers:cpanel-perl542
    steps:
      - name: Checkout cpanel-whm dependency
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          prove -lvw t/*.t
